version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=price_tracker
    ports:
      - 5432:5432
    volumes:
      - ./db-volume:/var/lib/postgresql/data